spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.21.9.220:3316/doc_collect?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: cntoor
      password: Ujmiui#Etfl6!LD0
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
system-config:
  #上传文件保存路径
  file-dir: /apps/dataQuery/uploadfile/
  project-url: http://172.25.117.52:12100/doc-collect/
# 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
server:
  tomcat:
    basedir: /apps/dataQuery/doc-collect/tmp

auth-url: http://172.25.117.56:31003
auth-frontier-url: http://172.25.117.56:31000

#统一认证
auth:
  client:
    id: testclientid
    secret: 123456
  config:
    need: true
  login:
    url: http://172.25.117.56:31000/frontier/auth/toLogin?redirect_url=http%3a%2f%2f172.25.117.52%3a12100%2fdoc-collect%2Floginback
  logout:
    url: http://172.25.117.56:8094/cas/logout

