spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.217.17.115:3306/doc_collect?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: fbi
      password: fbi
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
system-config:
  #上传文件保存路径
  file-dir: /usr/jar/D:/Project/doc-collect/collectfile/project
  # cas登录服务地址
  cas-service-url: http://10.217.17.116:8094/cas
  project-url: http://10.217.17.116:12100/doc-collect/
  portal-app: 备案项目管理
  portal-soap-url: http://10.217.17.116:18001/portal/intlDataSynchronizedService?wsdl
