spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/doc_collect?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 1234
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
system-config:
  #上传文件保存路径
  file-dir: D:/Project/doc-collect/collectfile/project
  project-url: http://127.0.0.1:12100/doc-collect/

#统一认证
auth:
  client:
    id: testclientid
    secret: 123456
  config:
    need: true
  login:
    url: http://59.212.226.45:31000/frontier/auth/toLogin?redirect_url=http%3a%2f%2f127.0.0.1%3a12100%2fdoc-collect%2Floginback
  logout:
    url: http://59.212.226.49:9302/cas/logout

auth-url: http://59.212.226.45:31987
auth-frontier-url: http://59.212.226.45:31000